aws_dbt_snowflake_project:
  outputs:
    dev:
      account: OSMUWQM-JW44621
      database: AIRBNB
      password: YatharthSharma123
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: YATHARTHJICS
      warehouse: COMPUTE_WH
  target: dev
yatharth_dbt:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-fc689a0e-9b05.cloud.databricks.com
      http_path: /sql/1.0/warehouses/f364ee13f60983ae
      schema: default
      token: dapi97e20d81bdc637141be0523daac3fa13
      type: databricks
  target: dev
